name: "not the smoke test"
on:
  workflow_run:
    workflows: [ "platformsh" ]
    types:
      - completed
  pull_request:
    branches:
      - master
env:
  GITHUB_TOKEN: ${{ secrets.DEVREL_TOKEN }}
jobs:
  i-too-will-test-pr:
    name: Test the PR environment
    runs-on: ubuntu-latest
    steps:
      - name: "I dont really do much"
        id: i-dont-do-much
        run: |
          echo "::notice::I ran"
  i-will-not-test:
    name: Not a smoke test
    runs-on: ubuntu-latest
    steps:
      - name: 'i do nothing'
        id: i-do-nothing
        run: |
          echo "::notice::I do nothing"
