name: "smoke test"
on:
  workflow_run:
    workflows: ["platformsh"]
    types:
      - completed
  pull_request:
    branches:
      - master
env:
    GITHUB_TOKEN: ${{ secrets.DEVREL_TOKEN }}
jobs:
  test-pr-env:
    name: Test the PR environment
    runs-on: ubuntu-latest
    steps:
      - name: 'Wait for psh and get target url'
        id: get-target-url
        uses: gilzow/retrieve-psh-prenv-url@main
        with:
           github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: 'Does Our App Work?'
        id: smokescreen
        run: |
          target_url=${{ steps.get-target-url.outputs.target_url }}
          echo "::notice::The target url returned from our github action: ${target_url}"
          #ok, so for whatever strange reason, our integration returns the http version of the PR environment, not https
          #hence to parameter expansion replacement.
          #we dont need the whole response (yet), just see if we get a 200
          response=$(curl -s -o /dev/null -I -w "%{http_code}" "${target_url//http:/https:}");
          echo "::notice::Response from server for our PR environment is ${response}"
          if [[ "200" == "${response}" ]]; then
            echo "::notice::Environment responded with http header 200"
          else
            echo "::error::Response from environment was something other than 200. Response returned was ${response}"
            exit 1;
          fi
