name: Trigger Source Operations on a Schedule
on:
    schedule:
        # Run at 5 after the hour, every hour
        - cron: '5 * * * *'
    workflow_dispatch:

env:
    PLATFORMSH_CLI_TOKEN: ${{ secrets.PLATFORMSHTOKEN }}
    PLATFORMSH_PROJECT_ID: ${{ secrets.PSHPROJID }}

jobs:
    trigger_src_op:
        name: Trigger Source Op
        runs-on: ubuntu-latest
        if: ${{ github.repository_owner == 'gilzow' }}
        steps:
            - name: 'Setup Python'
              uses: actions/setup-python@v2
              with:
                  python-version: '3.x'
            - uses: actions/checkout@v2
            - name: 'Run SourceOp Tools'
              run: |
                  # source ~/.bashrc
                  # which platform
                  printf "Beginning psh cli install...\n"
                  curl -fsS https://platform.sh/cli/installer | php
                  printf "Installation of psh cli complete. \n"
                  printf "Contents of PATH:\n%s\n" "${PATH}"
                  printf "What about the listing from /home/runner/.platformsh/bin/ ? \n"
                  ls -al /home/runner/.platformsh/bin/
                  #printf "Can I see a list of projects?\n"
                  #platform pro
                  #plat=$(which platform)
                  #lastcommand=$?
                  #printf "Output from which platform is: %s\n" "${plat}"
                  #if [ 0 != lastcommand ]; then
                    #printf "which platform command failed. Here is the contents of PATH: \n%s\n" "${PATH}"
                  #fi
                  #curl -fsS https://raw.githubusercontent.com/gilzow/source-operations/main/setup.sh | { bash /dev/fd/3 trigger-sopupdate; } 3<&0

